### ISSUE TITLE
NPM Install Not Found

### ISSUE THREAD

**Issue by stolinski** [mikadoplus/videojs-google-chromecast#1]
Installing via `npm install @videojs-google-chromecast/videojs-google-chromecast`return An unexpected error occurred: "https://registry.yarnpkg.com/@videojs-google-chromecast%2fvideojs-google-chromecast: Not found".

**Comment by mikadoplus** [comment]
Hi @stolinski, thats an error on the documentation, since a rely on the videojs plugin generator this was cretaed automatically, to install it just use npm install mikadoplus/videojs-google-chromecast.

**Comment by mikadoplus** [comment]
This package was created in order to work inside an electron-app who integrates a videojs in it, this on will rely on multicast DNS. It works still without it, and without electron but I think the Chromecast Tech will not be able to load, I'll soon make an update on this in order to work separately also. Be aware that this uses the last Google CAF Protocol if available on your network and will switch on CastV2 if not. Let me know if this works in order to close the issue and start a new one for improvement of the package.
